package com.taskmanagement.kotazk.entity.enums;

public enum ProjectPermission {
    BROWSE_PROJECT, // ADMIN, EDITOR, GUEST
    MODIFY_PROJECT, // ADMIN
    DELETE_PROJECT, // ADMIN
    MANAGE_ROLE, // ADMIN
    MANAGE_MEMBER,
    MANAGE_SECTION, // ADMIN
    ASSIGN_TASKS, // ADMIN
    ASSIGNABLE_USER, // ADMIN, EDITOR
    CREATE_TASKS, // ADMIN, EDITOR
    DELETE_TASKS, // ADMIN, EDITOR
    EDIT_TASKS, // ADMIN, EDITOR
    LINK_TASKS, // ADMIN, EDITOR
    SCHEDULE_TASKS, // ADMIN, EDITOR
    MANAGE_STATUS, // ADMIN
    MANAGE_PRIORITY, // ADMIN
    MANAGE_LABEL, // ADMIN
    MANAGE_TASK_TYPE, // ADMIN
    ADD_COMMENT, // ADMIN, EDITOR
    DELETE_ALL_COMMENT, // ADMIN
    DELETE_OWN_COMMENT, // ADMIN, EDITOR
    EDIT_ALL_COMMENT, // ADMIN
    EDIT_OWN_COMMENT, // ADMIN, EDITOR
    CREATE_ATTACHMENTS, // ADMIN, EDITOR
    DELETE_ALL_ATTACHMENTS, // ADMIN
    DELETE_OWN_ATTACHMENTS, // ADMIN, EDITOR
    MANAGE_REPORT
}
