package com.taskmanagement.kotazk.entity.enums;


public enum WorkSpacePermission {
    WORKSPACE_BASIC_INFO,
    WORKSPACE_SETTING,
    MANAGE_ROLE_SETTING,
    INVITE_MEMBER,
    BAN_KICK_MEMBER,
    CHANGE_MEMBER_ROLE,
    CHANGE_MEMBER_STATUS,
    ACCESS_PRIVATE_PROJECT,
    VIEW_GOAL,
    MANAGE_OWN_GOAL,
    MANAGE_ALL_GOAL,
    CREATE_PROJECT,
    MODIFY_OWN_PROJECT,
    MODIFY_ALL_PROJECT,
    DELETE_OWN_PROJECT,
    DELETE_ALL_PROJECT
}
