package com.taskmanagement.kotazk.entity.enums;


public enum WorkSpacePermission {
    BROWSE_WORKSPACE,
    WORKSPACE_SETTING, // ADMIN
    MANAGE_ROLE, // ADMIN
    MANAGE_MEMBER,
    RE_POSITION_PROJECT, // ADMIN
    BROWSE_PUBLIC_PROJECT, // ADMIN, EDITOR, GUEST
    BROWSE_PRIVATE_PROJECT, // ADMIN
    CREATE_PROJECT, // ADMIN, EDITOR
    MODIFY_OWN_PROJECT, // ADMIN, EDITOR
    MODIFY_ALL_PROJECT, // ADMIN
    DELETE_OWN_PROJECT, // ADMIN, EDITOR
    DELETE_ALL_PROJECT // ADMIN
}
